#!/usr/bin/env bash
# Script to audit subdomains of a domain

# Function to display subdomain information
display_info() {
    domain="$1"
    subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        dig_output=$(dig "$sub"."$domain" | awk '/^;; ANSWER SECTION:/{getline; print}')
        record_type=$(echo "$dig_output" | awk '{print $3}')
        destination=$(echo "$dig_output" | awk '{print $5}')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

# Main script logic
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi

domain="$1"
subdomain="$2"

display_info "$domain" "$subdomain"
