#!/usr/bin/env bash

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a directory for the default HTML file
sudo mkdir -p /var/www/html/
sudo chmod -R 755 /var/www

# Create the default HTML file
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null

# Create a separate Nginx configuration file for redirection
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/redirect
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

# Create a symbolic link to enable the new configuration
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Restart Nginx
sudo systemctl restart nginx
