#!/usr/bin/env bash
# This script configures a brand new Ubuntu machine to install Nginx and set a custom HTTP response header

# Uncomment to see the script run in action
#set -x

echo -e "Updating and doing some minor checks...\n"

function install() {
    command -v "$1" &> /dev/null

    if [ $? -ne 0 ]; then
	echo -e "Installing: $1\n"
	sudo apt-get update -y -qq && \
	    sudo apt-get install -y "$1" -qq
	echo -e "\n"
    else
	echo -e "${1} is already installed.\n"
    fi
}

# Install nginx
install nginx

echo -e "\nSetting up some minor stuff.\n"

# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
if [ -d "/var/www" ]; then
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
else
    sudo mkdir -p /var/www
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
fi

# Create directories if not present
for dir in /var/www/{html,error}; do
    if ! [ -d "$dir" ]; then
	mkdir -p "$dir"
    fi
done

# Creating new index
echo "Hello World!" > /var/www/html/index.html

# Create new error page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# Backup default server config file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

# Nginx server configuration with custom header
server_config=$(cat <<EOF
 EOF
		server {
		    listen 80 default_server;
		    listen [::]:80 default_server;
		    root /var/www/html;
		    index index.html index.htm index.nginx-debian.html;
		    server_name _;
		    add_header X-Served-By \$hostname;
		    location / {
			try_files \$uri \$uri/ =404;
		    }
		    if (\$request_filename ~ redirect_me) {
			   rewrite ^ https://th3-gr00t.tk/ permanent;
		       }
		       error_page 404 /error_404.html;
		       location = /error_404.html {
			   internal;
		       }
		}
		EOF
	     )

# Write the configuration to the default nginx site
echo "$server_config" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart nginx to apply changes
sudo systemctl restart nginx

EOF
