#!/usr/bin/env bash
# This script configures a brand new Ubuntu machine to install HAProxy and set up load balancing for web-01 and web-02

# Uncomment to see the script run in action
#set -x

echo -e "Updating and installing HAProxy...\n"

# Function to install packages
function install() {
    command -v "$1" &> /dev/null

    if [ $? -ne 0 ]; then
        echo -e "Installing: $1\n"
        sudo apt-get update -y -qq && \
        sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "${1} is already installed.\n"
    fi
}

# Install HAProxy
install haproxy

echo -e "\nConfiguring HAProxy...\n"

# Backup the original HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Create a new HAProxy configuration
haproxy_config=$(cat << EOF
defaults
    mode http
    timeout connect 10s
    timeout client 15s
    timeout server 15s

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 367003-web-01 52.7.166.204:80 check
    server 367003-web-02 52.91.146.234:80 check
EOF
)

# Write the new configuration to HAProxy config file
echo "$haproxy_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy to start on boot and restart the service
sudo systemctl enable haproxy
sudo systemctl restart haproxy

echo -e "\nHAProxy configuration completed.\n"
