#!/usr/bin/env bash
# Fix web server container so that Nginx is running as the nginx user.
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo pkill apache2
sudo service nginx start
